spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockservicedb?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create #none
    show-sql: true
    properties:
       hibernate:
         jdbc:
           time_zone: UTC
         show_sql: true
         format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
        

             
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:8191/oauth/check_token
#
#    client:
#      client-id: web
#  
